"""updated

Revision ID: 4ca767d8e9b1
Revises: 
Create Date: 2025-03-23 03:59:31.900450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca767d8e9b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('wallet_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('wallet_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
