"""add address

Revision ID: c82669e3661e
Revises: 4ca767d8e9b1
Create Date: 2025-07-29 06:13:55.625116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82669e3661e'
down_revision = '4ca767d8e9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algo', schema=None) as batch_op:
        batch_op.drop_constraint('algo_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('btc', schema=None) as batch_op:
        batch_op.drop_constraint('btc_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('connected_wallets', schema=None) as batch_op:
        batch_op.drop_constraint('connected_wallets_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('eth', schema=None) as batch_op:
        batch_op.drop_constraint('eth_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('poly', schema=None) as batch_op:
        batch_op.drop_constraint('poly_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('ripple', schema=None) as batch_op:
        batch_op.drop_constraint('ripple_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('send_money', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sol', schema=None) as batch_op:
        batch_op.drop_constraint('sol_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('stellar', schema=None) as batch_op:
        batch_op.drop_constraint('stellar_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('usdt', schema=None) as batch_op:
        batch_op.drop_constraint('usdt_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('xdc', schema=None) as batch_op:
        batch_op.drop_constraint('xdc_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xdc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('xdc_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('usdt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('usdt_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('stellar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stellar_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sol', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sol_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('send_money', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('ripple', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ripple_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('poly', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('poly_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('eth', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('eth_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('connected_wallets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('connected_wallets_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('btc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('btc_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('algo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('algo_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
